{{- range .Values.namespaces }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemon
  namespace: {{ . }}
spec:
  selector:
    matchLabels:
      app: nginx-daemon
  template:
    metadata:
      labels:
        app: nginx-daemon
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
{{- end }}
